# Using lightweight alpine image
FROM python:3.9

# Install cron
RUN apt-get update; apt-get install -y cron

# Install Requirements
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Defining working directory and adding source code
COPY app/ ./

# Start app
EXPOSE 8501
ENTRYPOINT ["sh", "entrypoint.sh"]