version: "3"
services:
  cours:
    image: cours:latest
    ports:
      - "8080:8080"

  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
